### ISSUE TITLE
Intermittent server error when attempting to reach billing

### ISSUE THREAD

**Issue by kennedyrose** [escaladesports/zygote-cart#210]
When attempting to reach the 3rd page of checkout (Billing information), the system does not move forward, and after a moment of spinning, throws the following error, “We're sorry! There was an error with the server. Your information was not placed. Please try again later.”

"1. Go to Website
2. Add item to cart
3.Cart window will open
4. Click ""Secure Checkout""
5. Enter valid details
6. Click ""Next Step""
7. Cart window will throw an error message after some loading time"

"Internet Explorer Ver. 11.706.17134.0
Microsoft Edge Ver. 42.17134.1.0
Firefox Ver. 66.0.3
Chrome Ver. 73.0.3683.103"

**Comment by suhay** [comment]
Not able to replicate
