### ISSUE TITLE
Free Shipping for Continental US not calculating

### ISSUE THREAD

**Issue by kennedyrose** [escaladesports/zygote-cart#213]
The website states "Free shipping for orders $20 and over", but this is not reflected in the Checkout area.

"Internet Explorer Ver. 11.706.17134.0
Microsoft Edge Ver. 42.17134.1.0
Firefox Ver. 66.0.3
Chrome Ver. 73.0.3683.103"

https://drive.google.com/open?id=1H8Qx8rH_-20XptvrPEA24A8bqQiIHmj7

**Comment by suhay** [comment]
This is placeholder text, please disregard
