### ISSUE TITLE
iOS devices are having scrolling issues

### ISSUE THREAD

**Issue by kennedyrose** [escaladesports/zygote-cart#217]
When scrolling on the cart window, the main website scrolls as well. This is causing some issues when trying to scroll on the cart window

"iPhone 7/11.4.1
iPadMini/ 11.4.1
iPhone 5s/ 12.0.1
iPadAir/ 12.1.4"

https://drive.google.com/open?id=1J94dRHTVD3lP3x8wUXtH8k4jjN2_kpqc

**Comment by suhay** [comment]
I added an overflow handler that appears to be working on most cases. Was not able to get it to work on iOS on browser stack but that may be an emulation error.
