### ISSUE TITLE
Certain items are failing to concatenate in cart

### ISSUE THREAD

**Issue by kennedyrose** [escaladesports/zygote-cart#219]
When going to the 'Shipping Detail' page in the 'Cart' window certain item's name will fail to concatenate.

"Internet Explorer Ver. 11.706.17134.0
Microsoft Edge Ver. 42.17134.1.0
Firefox Ver. 66.0.3
Chrome Ver. 73.0.3683.103 (Mac and Windows)
Safari Ver. 12.0 (MAC)
Galaxy Tab E/ 6.0.1
Galaxy Tab A/ 7.1.1
Nexus 6P/ 8.1.0
Pixel XL/ 9.0
iPhone 7/11.4.1
iPadMini/ 11.4.1
iPhone 5s/ 12.0.1
iPadAir/ 12.1.4"

https://drive.google.com/open?id=1eP79GAIrljwvv1wPxaV-LqtuyuRjB12e

**Comment by suhay** [comment]
Unable to replicate.

**Comment by kennedyrose** [comment]
I can replicate with this item: https://zygote-test--escalade-sports.netlify.com/product/p1850

**Comment by suhay** [comment]
Added regex to any {name} output to handle double and single quotes. It's very sporadic where it's happening so it must be how salsify is sending it to us.
