### ISSUE TITLE
 'Cart' window scrolls to the bottom of the page when selecting an input box

### ISSUE THREAD

**Issue by kennedyrose** [escaladesports/zygote-cart#224]
When a user selects any data input box on the 'Cart' window  the page scrolls to the very bottom. It will jump back up to the selected input box when user starts inputting data.

"Galaxy S5/6.0.1 
Galaxy S6 Edge/7.0
Nexus 6P/ 8.1.0 
Pixel XL/ 9.0 "

https://drive.google.com/open?id=1meNJfjYDVMoU9Av38JJWS8dR8Ftp6KPE

**Comment by suhay** [comment]
Can't replicate
