### ISSUE TITLE
Tax ammount won't change on address update

### ISSUE THREAD

**Issue by kennedyrose** [escaladesports/zygote-cart#233]
Steps to reproduce:

1. Start checking out with an Indiana address
2. Click next
3. Wait for tax to change to Indiana tax
4. Go back
5. Fill out a California address (11910 WAGNER ST, Culver City, CA 90230)
6. Click next
7. Notice tax still lists Indiana tax

**Comment by tbaustin** [comment]
@kennedyrose  should be fixed now
